#!/usr/bin/env python3
"""
Export Generators for OSINT MCP Enterprise Gateway.
Supports Markdown, JSON, CSV, and PDF export formats.
"""

import csv
import io
import json
import os
import re
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from .models import OSINTResult


REPORT_BRANDING = os.getenv("OSINT_REPORT_BRANDING", "OSINT MCP Enterprise Gateway")
REPORT_LOGO_URL = os.getenv("OSINT_REPORT_LOGO_URL", "")


class MarkdownExporter:
    @staticmethod
    def export(
        results: List[Dict[str, Any]],
        title: str = "OSINT Investigation Report",
        target: str = "",
        analyst: str = "",
        include_raw: bool = False,
    ) -> str:
        lines = [
            f"# {title}",
            "",
            f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
            f"**Target:** {target}" if target else "",
            f"**Analyst:** {analyst}" if analyst else "",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
        ]

        total_found = 0
        tools_used = set()
        for result in results:
            tool = result.get("tool", "unknown")
            tools_used.add(tool)
            if result.get("found"):
                total_found += 1

        lines.extend([
            f"- **Tools Used:** {', '.join(sorted(tools_used))}",
            f"- **Targets Found:** {total_found} / {len(results)}",
            f"- **Timestamp:** {datetime.now(timezone.utc).isoformat()}",
            "",
            "## Detailed Results",
            "",
        ])

        for idx, result in enumerate(results, 1):
            tool = result.get("tool", "unknown")
            found = result.get("found", False)
            status = result.get("status", "unknown")
            accounts = result.get("accounts", [])
            email_info = result.get("email_info", {})
            domain_info = result.get("domain_info", {})
            confidence = result.get("confidence", "unknown")
            exec_time = result.get("execution_time_ms", 0)

            lines.extend([
                f"### {idx}. {tool.title()} ({status})",
                "",
                f"- **Target:** {result.get('target', 'N/A')}",
                f"- **Found:** {'Yes' if found else 'No'}",
                f"- **Confidence:** {confidence}",
                f"- **Execution Time:** {exec_time}ms" if exec_time else "",
            ])

            if accounts:
                lines.extend([
                    "",
                    f"#### Accounts Found ({len(accounts)})",
                    "",
                    "| Platform | URL |",
                    "|---------|-----|",
                ])
                for account in accounts[:50]:
                    platform = account.get("platform", "unknown")
                    url = account.get("url", "N/A")
                    lines.append(f"| {platform} | {url} |")

            if email_info and isinstance(email_info, dict):
                associated = email_info.get("associated_accounts", [])
                if associated:
                    lines.extend([
                        "",
                        "#### Associated Accounts",
                        "",
                    ])
                    for acc in associated[:20]:
                        lines.append(f"- {acc}")

            if domain_info and isinstance(domain_info, dict):
                emails = domain_info.get("emails", [])
                hosts = domain_info.get("hosts", [])
                if emails:
                    lines.extend([
                        "",
                        "#### Emails Discovered",
                        "",
                    ])
                    for email in emails[:20]:
                        lines.append(f"- {email}")
                if hosts:
                    lines.extend([
                        "",
                        "#### Hosts Discovered",
                        "",
                    ])
                    for host in hosts[:20]:
                        lines.append(f"- {host}")

            if include_raw and result.get("raw_output"):
                raw = result.get("raw_output", "")
                if len(raw) > 2000:
                    raw = raw[:2000] + "\n...[truncated]..."
                lines.extend([
                    "",
                    "#### Raw Output",
                    "",
                    "```",
                    raw,
                    "```",
                ])

            lines.append("")

        lines.extend([
            "---",
            "",
            f"*Generated by {REPORT_BRANDING} on {datetime.now(timezone.utc).isoformat()}*",
        ])

        return "\n".join(lines)


class CSVExporter:
    @staticmethod
    def export_accounts(results: List[Dict[str, Any]]) -> str:
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow([
            "tool",
            "target",
            "target_kind",
            "platform",
            "url",
            "username",
            "status",
            "confidence",
            "found",
            "timestamp",
            "execution_time_ms",
        ])

        for result in results:
            tool = result.get("tool", "")
            target = result.get("target", "")
            target_kind = result.get("target_kind", "")
            accounts = result.get("accounts", [])

            if not accounts:
                writer.writerow([
                    tool,
                    target,
                    target_kind,
                    "",
                    "",
                    "",
                    result.get("status", ""),
                    result.get("confidence", ""),
                    "Yes" if result.get("found") else "No",
                    result.get("timestamp", ""),
                    result.get("execution_time_ms", ""),
                ])
            else:
                for account in accounts:
                    writer.writerow([
                        tool,
                        target,
                        target_kind,
                        account.get("platform", ""),
                        account.get("url", ""),
                        account.get("username", ""),
                        result.get("status", ""),
                        result.get("confidence", ""),
                        "Yes" if result.get("found") else "No",
                        result.get("timestamp", ""),
                        result.get("execution_time_ms", ""),
                    ])

        return output.getvalue()

    @staticmethod
    def export_summary(results: List[Dict[str, Any]]) -> str:
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow([
            "tool",
            "target",
            "target_kind",
            "found",
            "accounts_count",
            "confidence",
            "status",
            "execution_time_ms",
            "sites_checked",
            "sites_found",
            "timestamp",
        ])

        for result in results:
            accounts = result.get("accounts", [])
            writer.writerow([
                result.get("tool", ""),
                result.get("target", ""),
                result.get("target_kind", ""),
                "Yes" if result.get("found") else "No",
                len(accounts) if accounts else 0,
                result.get("confidence", ""),
                result.get("status", ""),
                result.get("execution_time_ms", ""),
                result.get("sites_checked", ""),
                result.get("sites_found", ""),
                result.get("timestamp", ""),
            ])

        return output.getvalue()


class JSONExporter:
    @staticmethod
    def export(
        results: List[Dict[str, Any]],
        title: str = "OSINT Investigation Report",
        target: str = "",
        include_raw: bool = False,
    ) -> str:
        export_data = {
            "title": title,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "target": target,
            "results_count": len(results),
            "results": results,
        }

        if not include_raw:
            for result in export_data["results"]:
                result.pop("raw_output", None)

        return json.dumps(export_data, indent=2, ensure_ascii=False)


class PDFExporter:
    @staticmethod
    def export(
        results: List[Dict[str, Any]],
        title: str = "OSINT Investigation Report",
        target: str = "",
        analyst: str = "",
        output_path: Optional[str] = None,
    ) -> str:
        markdown = MarkdownExporter.export(
            results=results,
            title=title,
            target=target,
            analyst=analyst,
        )

        text_content = MarkdownExporter.export(
            results=results,
            title=title,
            target=target,
            analyst=analyst,
            include_raw=False,
        )

        has_reportlab = False
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.pdfgen import canvas
            from reportlab.lib.units import inch
            from reportlab.lib.colors import HexColor
            has_reportlab = True
        except ImportError:
            pass

        if has_reportlab and output_path:
            try:
                return PDFExporter._generate_pdf(
                    text_content,
                    output_path,
                    title,
                    target,
                )
            except Exception:
                pass

        safe_name = re.sub(r"[^A-Za-z0-9._-]+", "_", title.strip())
        fallback_path = output_path or f"reports/{safe_name}.txt"
        fallback_file = Path(fallback_path)
        fallback_file.parent.mkdir(parents=True, exist_ok=True)
        fallback_file.write_text(text_content, encoding="utf-8")
        return str(fallback_file)

    @staticmethod
    def _generate_pdf(
        text_content: str,
        output_path: str,
        title: str,
        target: str,
    ) -> str:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
        from reportlab.lib.units import inch
        from reportlab.lib.colors import HexColor

        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        c = canvas.Canvas(str(output_file), pagesize=letter)
        width, height = letter

        y_position = height - 0.75 * inch
        margin = 0.75 * inch
        line_height = 14

        c.setFont("Helvetica-Bold", 18)
        c.drawString(margin, y_position, title[:80])
        y_position -= line_height * 2

        c.setFont("Helvetica", 10)
        c.drawString(margin, y_position, f"Target: {target}")
        y_position -= line_height

        c.drawString(margin, y_position, f"Generated: {datetime.now(timezone.utc).isoformat()}")
        y_position -= line_height * 2

        c.setStrokeColor(HexColor("#cccccc"))
        c.line(margin, y_position + 5, width - margin, y_position + 5)
        y_position -= line_height

        c.setFont("Helvetica", 9)
        for line in text_content.split("\n"):
            if y_position < margin:
                c.showPage()
                y_position = height - margin

            if line.startswith("# "):
                c.setFont("Helvetica-Bold", 14)
                c.drawString(margin, y_position, line[2:][:100])
                y_position -= line_height
                c.setFont("Helvetica", 9)
            elif line.startswith("## "):
                c.setFont("Helvetica-Bold", 12)
                c.drawString(margin, y_position, line[3:][:100])
                y_position -= line_height
                c.setFont("Helvetica", 9)
            elif line.startswith("### "):
                c.setFont("Helvetica-Bold", 10)
                c.drawString(margin, y_position, line[4:][:100])
                y_position -= line_height
                c.setFont("Helvetica", 9)
            elif line.startswith("**") and line.endswith("**"):
                c.setFont("Helvetica-Bold", 9)
                c.drawString(margin, y_position, line[2:-2][:100])
                y_position -= line_height
                c.setFont("Helvetica", 9)
            elif line.startswith("- "):
                c.drawString(margin + 10, y_position, line[:90])
                y_position -= line_height
            elif line.startswith("|"):
                pass
            elif line == "---":
                c.line(margin, y_position + 5, width - margin, y_position + 5)
                y_position -= line_height
            elif line.strip():
                c.drawString(margin, y_position, line[:100])
                y_position -= line_height
            else:
                y_position -= line_height / 2

        c.setFont("Helvetica-Oblique", 8)
        c.drawString(
            margin,
            margin / 2,
            f"Generated by {REPORT_BRANDING} | {datetime.now(timezone.utc).isoformat()}",
        )

        c.save()
        return str(output_file)


class ExporterFactory:
    FORMATS = {"markdown", "md", "json", "csv", "pdf", "txt"}

    @classmethod
    def export(
        cls,
        results: List[Dict[str, Any]],
        format: str = "markdown",
        title: str = "OSINT Report",
        target: str = "",
        analyst: str = "",
        output_dir: str = "reports",
        filename: Optional[str] = None,
    ) -> Dict[str, Any]:
        format = format.lower().strip()
        if format not in cls.FORMATS:
            format = "markdown"

        if not filename:
            safe_name = re.sub(r"[^A-Za-z0-9._-]+", "_", title.strip())
            if not safe_name:
                safe_name = "osint_report"
            extension = {"pdf": "pdf", "csv": "csv", "json": "json"}.get(format, "md")
            filename = f"{safe_name}.{extension}"

        output_path = Path(output_dir) / filename
        output_path.parent.mkdir(parents=True, exist_ok=True)

        if format in {"markdown", "md"}:
            content = MarkdownExporter.export(
                results=results,
                title=title,
                target=target,
                analyst=analyst,
            )
            output_path.write_text(content, encoding="utf-8")
        elif format == "json":
            content = JSONExporter.export(
                results=results,
                title=title,
                target=target,
            )
            output_path.write_text(content, encoding="utf-8")
        elif format == "csv":
            content = CSVExporter.export_summary(results)
            output_path.write_text(content, encoding="utf-8")
        elif format == "pdf":
            content = PDFExporter.export(
                results=results,
                title=title,
                target=target,
                analyst=analyst,
                output_path=str(output_path),
            )
        else:
            content = MarkdownExporter.export(
                results=results,
                title=title,
                target=target,
                analyst=analyst,
            )
            output_path.write_text(content, encoding="utf-8")

        return {
            "success": True,
            "path": str(output_path),
            "format": format,
            "filename": filename,
            "size_bytes": output_path.stat().st_size if output_path.exists() else 0,
        }
